name: Publish

on:
  push:
    branches:
      - '**'
    paths:
      - 'Dockerfile'
      - '.github/workflows/main.yml'
      - 'docker-bake.hcl'
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker
        uses: docker/login-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          username: "cyb3rjak3"
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login To GitHub
        uses: docker/login-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: cyb3rjak3/alpine-tomcat,ghcr.io/cyb3r-jak3/alpine-tomcat
          labels: |
            org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/alpine-tomcat.git
            maintainer=Cyb3r Jak3 git@cyberjake.xyz
            org.opencontainers.image.vendor=cyb3rjak3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v3

      - name: Build
        uses: docker/bake-action@v3
        with:
          files: |
            ${{ steps.meta.outputs.bake-file }}
            ./docker-bake.hcl
          targets: release
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
