name: Publish

on:
  push:
    branches:
      - '**'
    paths:
      - 'Dockerfile'
      - '.github/workflows/main.yml'
      - 'docker-bake.hcl'
    tags:
      - "v*"
  pull_request:
    branches:
      - main


env:
  DOCKER_USERNAME: cyb3rjak3

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to Docker
        uses: docker/login-action@v3
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login To GitHub
        uses: docker/login-action@v3
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: cyb3rjak3/alpine-tomcat,ghcr.io/cyb3r-jak3/alpine-tomcat
          labels: |
            org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/alpine-tomcat.git
            maintainer=Cyb3r Jak3 git@cyberjake.xyz
            org.opencontainers.image.vendor=cyb3rjak3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: Build
        uses: docker/bake-action@v6
        with:
          files: |
            ${{ steps.meta.outputs.bake-file }}
            ./docker-bake.hcl
          targets: release
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

  Update-DockerHub:
    runs-on: ubuntu-latest
    name: Update DockerHub Descriptions
    needs: Publish
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyb3rjak3/alpine-tomcat
